package dsm.pick2024.domain.timetable.enum

enum class Subject(
    val subjectName: String
) {
    ART("미술"),
    PHYSICAL_COMPUTING("피지컬컴퓨팅"),
    COMPUTER_NETWORK("컴퓨터 네트워크"),
    OPERATING_SYSTEM("운영체제"),
    FIRMWARE_IMPLEMENTATION("정보통신기기 펌웨어구현"),
    KOREAN("국어"),
    AI_PROJECT_PRACTICE("인공지능 프로젝트 실무"),
    SOFTWARE_ENGINEERING_PRACTICE("소프트웨어공학 실무"),
    INTEGRATED_SOCIAL_STUDIES("통합사회"),
    AI_THEORY("인공지능론"),
    FRONTEND_PROGRAMMING("프론트엔드 프로그래밍"),
    INTEGRATED_SCIENCE("통합과학"),
    DATA_STRUCTURES("자료구조"),
    EXERCISE_AND_HEALTH("운동과 건강"),
    PROJECT_PRACTICE_II("프로젝트실무Ⅱ"),
    ENGLISH_I("영어Ⅰ"),
    LITERATURE("문학"),
    CREATIVE_ACTIVITY("창체"),
    LINUX_SYSTEM_PROGRAMMING("리눅스 시스템 프로그래밍"),
    PROBABILITY_AND_STATISTICS("확률과 통계"),
    MATHEMATICS("수학"),
    BASIC_WEB_PROGRAMMING("웹프로그래밍기초"),
    EMBEDDED_RTOS("임베디드 실시간 운영체제"),
    KOREAN_HISTORY("한국사"),
    EMBEDDED_SYSTEMS("임베디드 시스템"),
    MICROPROCESSOR_APPLICATIONS("마이크로프로세서응용"),
    DIGITAL_FORENSICS("디지털 포렌식"),
    WEB_PROGRAMMING("웹프로그래밍"),
    SYSTEM_MAINTENANCE("시스템 유지보수관리"),
    MICROPROCESSOR_CONTROL("마이크로프로세서 제어"),
    PCB_DEVELOPMENT("정보통신기기 PCB보드 개발"),
    ENGLISH("영어"),
    JAVA_PROGRAMMING("자바 프로그래밍"),
    EMBEDDED_LINUX_PROGRAMMING("임베디드 리눅스 프로그래밍"),
    CAREER_AND_JOB("진로와 직업"),
    ALGORITHM_PRACTICE("알고리즘실무"),
    AI_UTILIZATION("인공지능 활용"),
    SYSTEM_CHECK_MAINTENANCE("시스템 점검관리"),
    SERVER_PROGRAMMING("서버 프로그래밍"),
    HACKING("해킹"),
    MUSIC("음악"),
    SPORTS("체육"),
    BIG_DATA_ANALYSIS("빅데이터 분석");
}
